### ISSUE TITLE
Problem with rx_subscribeRowsToCellWithIdentifier

### ISSUE THREAD

**Issue by dtartaglia** [kzaher/RxSwift#20]
`func rx_subscribeRowsToCellWithIdentifier<E, Cell where E : AnyObject, Cell: UITableViewCell>
        (cellIdentifier: String, configureCell: (UITableView, NSIndexPath, E, Cell) -> Void)
        (source: Observable<[E]>)
        -> Disposable`

I want to be able to configure my cells with structs, but since `E` must be an `AnyObject` I can't. Can that be changed to `any`?

**Comment by kzaher** [comment]
Agreed, this should be fixed.

**Comment by alcarvalho** [comment]
I was trying to make this fix, but I stumbled on my lack of experience with Swift. After changing `AnyObject` to `Any`, I get the following error:

[UICollectionView+Rx.swift:123:37](https://github.com/alcarvalho/RxSwift/blob/cfd749417f846fe14cd747ad48cc29e0911263e6/RxCocoa/RxCocoa/iOS/UICollectionView%2BRx.swift#L123): Cannot assign a value of type '[E]' to a value of type '[Any]'

If someone could help me, I would be happy to create a PR with the fixes. :wink:

**Comment by kzaher** [comment]
Hi Andre :)

Thnx for your interest in helping this project.

I've started to work on this problem before a couple of weeks. I have a [solution here](https://github.com/kzaher/RxSwift/tree/feature/typed-data-source-and-sections).

As you can see, it's not trivial because of the way swift generics interact with objective-c runtime, but should be really sweet to use it.

The reason why it's not merged yet into develop branch and into release pipeline is because I would like to add out of the box incremental updates in RxCocoa project for UITableView and UICollectionView.

The reason why I would like to do that is because I want to make sure that public interface makes sense for incremental updates also. I guess I could just design it so it makes sense, but proof by demonstration is best IMHO :)

Here are the ways how you can help us get this finished soon:
* you can help me investigate partial design algorithm (I need to know how exactly do UITableView internals work). Although it looks like there is tons of information on the internet, all of the information is partial and lacking vital pieces.
* after I finish changes for UITableView (maybe today or tomorrow), you can help me port those changes to UICollectionView. It should be pretty much analog to UITableView solution.
* you can give me feedback on solution presented here https://github.com/kzaher/RxSwift/tree/feature/typed-data-source-and-sections, and suggest a better one :)

We can chat more about this in slack channel if you like :) #uitableview_interface
