### ISSUE TITLE
Question about where to put reactive code.

### ISSUE THREAD

**Issue by dtartaglia** [kzaher/RxSwift#24]
I currently have my reactive code in the viewDidLoad method, and I dispose everything in the deinit.

However, I noticed that when I exit my view controller, the deinit is never called. I confirmed that the view controller is not getting reused, and that my memory footprint goes up with every entry/exit of my view controller, but no leaks are detected...

Does anybody know what is going on?

**Comment by manumax** [comment]
Are you running instruments against simulator or a real device to check memory footprint? If the answer is simulator, try again using a real device.
About `deinit` never called, have you checked for reference cycles? They won't show as memory leaks (since they aren't). Another thing you could do, it's to consider using `viewWillAppear` and `viewDidAppear` to create and dispose your reactive code.

**Comment by kzaher** [comment]
Hi @dtartaglia, leaks profiler in Xcode is useless. Apple has made a small dirty marketing trick there :)

If you use allocations profiler, you should see number of view controller objects in memory. 

Unfortunately, Apple has bug with profiling allocations on simulator, so you'll need to run profiler on real device, otherwise it won't show instances of some of your objects :(

@manumax is right, you have retain cycle somewhere.

We can probably discuss things like that in slack, because otherwise we'll spam whoever is watching this repository :)

**Comment by dtartaglia** [comment]
FYI. I found the retain cycle and fixed it.
