### ISSUE TITLE
var rx_tap instead of func rx_tap

### ISSUE THREAD

**Issue by dtartaglia** [kzaher/RxSwift#27]
Currently the library uses code like:
```public func rx_text() -> Observable<String> { ... }```

What would it take to convince you to use something like the below instead?
```public var rx_text: Observable<String> { ... }```

**Comment by kzaher** [comment]
I've actually tried using properties in extensions initially, but for some reason compiler was complaining :(, so I've said, what the hell, I'll just use functions.

It looks like compiler isn't complaining in swift 1.2 and Xcode 6.3.2, so we can use properties wherever possible :)

**Comment by dtartaglia** [comment]
I'm willing to make this change if you want... but it's a breaking change. Let me know what you want to do.

**Comment by kzaher** [comment]
Ideally, I would always want to be backwards compatible, and will try to be.

If there are some obvious mistakes in the API or ugly interface that could be easily improved, I would like to correct it as soon as possible (before there are tons of code that depend on it).

I don't expect these changes will aggravate users, because they will make their code more clear, and they would just need to remove redundant ().

If you want to help the project, go for it :+1: and make those changes.

**Comment by bontoJR** [comment]
I have a consideration about this: we are in the early times of the project, breaking changes are always bad, but are tolerated in early stages. I would prefer to have a breaking change now, rather than in a year or so while using the framework in an app in production.

**Comment by nathankot** [comment]
Hey guys, I just started using this library and it looks like `rx_text` etc.. has already been swapped over to being properties? In that case the readme is a little confusing because it still shows it as a method

**Comment by kzaher** [comment]
Hi, 

sorry, readme probably has stale information.
