### ISSUE TITLE
combineLatest without resultSelector

### ISSUE THREAD

**Issue by ashfurrow** [kzaher/RxSwift#35]
Something I liked from ReactiveCocoa 2 was the `and` operator, which operated on two signals sending `NSNumber`s wrapping `BOOL`s. Swift gives us an opportunity to do something safer with the type system. 

It would be cool if we had a `combineLatest` that took two (or whatever) `Observable<Bool>` (or comparable or whatever) and returned an `Observable<(Bool, Bool)>`. Something like:

```swift
func combineLatest(source1: Observable<Bool>, source2: Observable<Bool>) -> Observable<(Bool, Bool)> {
    return combineLatest(source1, source2, { (a: Bool, b: Bool) -> (Bool, Bool) in
        return (a, b)
    })
}
```

Then we can also have operators like `and` and `or`. 

```swift
func and(observable: Observable<(Bool, Bool)>) -> Observable<Bool> {
    return observable
        >- map({ (thing) -> Bool in
            return thing.0 && thing.1
        })
}
```

Which lets developers write code like this: 

```swift
combineLatest(emailIsValid, passwordIsValid)
    >- and
    >- signupButton.rx_subscribeEnabledTo
    >- disposeBag.addDisposable
```

Which would be :ok_hand: 

Now, this gets kind of crazy since ideally you could have an arbitrary number of bools in your tuple of `Bool`s. We could use an array or set or some other internal data structure – but I think abstracting away the logic of `&&`ing a bunch of `Bool`s together into an expressive function would be in the spirit of FRP.

**Comment by dtartaglia** [comment]
ReactiveX already has and/then/when. I would rather see all the standard operators first, before starting on custom ones.

**Comment by ashfurrow** [comment]
Hmm, I see that. ([Here's a link](http://reactivex.io/documentation/operators/and-then-when.html) for anyone else looking.) I agree that priority should be placed on standard stuff, but I don't think you understood my question. 

I am opening issues as I encounter things that I'd like to see but can't find, and I'm coming from a ReactiveCocoa-only background. Sometimes I'm going to not know the ReactiveX jargon that would describe my question. 

In this case, it looks like the `And` or `Zip` operators might do what I'm looking for, which is great. I appreciate being pointed in the correct direction. 

As a side-note, linking to relevant documentation or describing how `And`/`Then`/`When` work would be far more helpful than shutting me down by telling me what I'm looking for isn't important. We're all in this together :+1:

**Comment by dtartaglia** [comment]
Sorry Ash, it wasn't my intention to shut you down. (I like your `rx_subscribeEnabledTo` suggestion BTW.)

You are right that AFAIK, and/then/when have not been added to this library yet so asking for one of them makes a lot of sense. 

I'm also glad to have someone with a ReactiveCocoa background on-board here. We need help outlining the differences and likenesses between the two libraries.

**Comment by ashfurrow** [comment]
Cool, sounds awesome. I'm quite excited to see a variety of FRP libraries for iOS and OS X! I think we all bring a unique perspective on things and I'm really thrilled to have the opportunity to work together on such a nascent, but important library.

**Comment by kzaher** [comment]
Hi Ash,

It looks like night was interesting :)

So here is what I'm thinking. You are correct, the code that you've written has really awesome readability. And we need to figure out how to allow users to write readable code.

Here are existing options that are kind of equivalent of those

```swift
combineLatest(emailIsValid, passwordIsValid, and)
            >- signupButton.rx_subscribeEnabledTo
            >- disposeBag.addDisposable
```

```swift
combineLatest(emailIsValid, passwordIsValid) { $0 && $1 }
            >- signupButton.rx_subscribeEnabledTo
            >- disposeBag.addDisposable
```

The third options is to do something that you've done. Just defining your own operator locally. I think we all agree your code is the most readable one.

On the other hand, I do need some way of deciding what should enter RxSwift library. If I add boolean `and` operator, then I should probably add all 10 overloads for all combinations of arguments, even though it's not really realistic that somebody will be using `and` for 10 boolean arguments :)

And what's worse, I should probably add `or`, and `xor` and possibly some others too :)

Swift compiler is still delicate peace of software, so I'm afraid adding more overloads will even make it behave worse.

Then, there is also confusion with Rx [and](http://reactivex.io/documentation/operators/and-then-when.html) operator.

So these are reasons for and against as I see them. 

I think the real question here is what is the definition of RxSwift project. What should it contain? What is it's purpose (also the same for RxCocoa project). If we don't have that clearly defined, people will be confused.

This is how I see their responsibility right now. Maybe I should revise it in future if it becomes inadequate.

RxSwift should be the purest core of the system. The foundation of the entire project. It's responsibility is to provide highly optimized basic sequence [operators](http://reactivex.io/documentation/operators.html).
Reason why I would want that is because if some mathematical abstraction works on so many different platforms and environments (native clients/servers/web clients), it's reasonable to assume that it will work on one more. You also have consistency between platforms. I want to be able to talk with other teams in the same common language, and read code in other languages.
All of the operators that enter this project should not only be thoroughly unit tested but their code validity should be proved. Unit tests are necessary and extremely useful, but they don't prove correctness, and especially not in multithreaded environment.
It will ofc also include basic platform scheduler implementations. 
It will also possibly contain convenience functions that we can't live without and that provide significant value for future optimizations (I really think that `variable`/`sharedWithCachedLastResult` is that function). The reason why I feel it's so valuable is because it's probably the most common way of optimizing cold observables for performance. I was really having a hard time fighting this one out. If you look at commit history, it slowly crawled into RxSwift core. Right now it's just an alias for `replay(1) >- refCount`, but since it's probably going to be used often, having a single place where I can apply optimizations in future for everybody is valuable enough IMHO to include it there.
Because of all of this, it will probably be a lot harder to make PRs for bigger features (like operators), but easy for bugfixes (although I'm hoping there shouldn't be many serious bugs because of all of the measures :) This has it's drawbacks, but believe me, porting those operators is tedious and exhausting work. There isn't much room for being creative here. It's really similar to translating math books :)
The biggest help I need here is actually proving that operators behave like they should in RxSwift. If somebody proves to me that I've missed some case for some operator, and makes a PR to fix that edge case, that has extremely high value for this project, will have my gratitude and PR will be merged immediately.
Having said that, I do see great value for external independent projects that provide common convenience Rx operators optimized for specific use cases or operators that ease the transition from other reactive frameworks. 

RxCocoa should contain default out of the box integration with Foundation/Cocoa/UIKit environment. This is where consistency doesn't matter so much because this is platform specific code, but having some consistency would be good idea. This is where we'll probably have biggest discussion regarding APIs.
Making PRs to get merged here should be a lot easier because integrations are pretty simple, they usually rely on reusing building blocks from RxSwift.

So how to resolve all of this?

* I can investigate how to maybe include `combineLatest` without lambda
```swift
func combineLatest<T1, T2>(source1: Observable<T1>, source2: Observable<T2>) -> Observable<(T1, T2)>
```
This seems to me like a possibly useful thing to have, it's well defined and can be considered as adapted `combineLatest` operator version in context of swift. If I include this, I don't have to include 40 more functions, just 10 :)

* as far as for `and` operator, I really feel it's better not including it right now in RxSwift because of the mentioned reasons.
I think that adding a lot of specific use case convenience operators to RxSwift would be convenient, but could cause negative effect too easily. I would really for people to hack around with framework and see how easy it is to create their own compositions. They can also create their own dialects, their own custom optimized versions, etc. Hacking around with something (composing) should be easy, and I think RxSwift really shines here.

I think it's awesome that you can in 10 lines of code create something that is so much more readable for particular use case, and I do see great value of sharing those modifications, but I would just want to be careful where to include them.

Kruno

**Comment by dtartaglia** [comment]
I'm still setting up my new computer so I can't test this myself right now, but can't you already do something like this?
```
combineLatest(emailIsValid, passwordIsValid, &&)
            >- signupButton.rx_subscribeEnabledTo
            >- disposeBag.addDisposable
```

**Comment by kzaher** [comment]
Hi Daniel,

yeah, theoretically this should work and I really thought this does work (I could have swore that I've tried that once), but don't think swift compiler is polished enough. Tried it myself this morning and it looks like it's not working :(

**Comment by ashfurrow** [comment]
Yeah, that was my initial try, which I thought should work, since this does:

```swift
let array = [1,4,2]
array.sort(<)
```

**Comment by kzaher** [comment]
<img src="http://why-am-i-always-tired.org/wp-images/doctor-shrug_s.jpg" />

**Comment by kzaher** [comment]
Hi Ash,

I knew I wasn't crazy :)

you can use 

```
let aggregateSubscriber = returnElements(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
        >- aggregate(0, +)
        >- subscribeNext { value in
            println("\(value)")
    }
```

and 

```
let c = combineLatest(a, b, +)
        
        var latestValue: Int?
        
        let subscription = c >- subscribeNext { next in
            latestValue = next
        }
```

I just think that Swift compiler is being little drama queen with `&&`.

I think that when Swift compiler becomes little more mature, it will also be be able to compile
```
combineLatest(emailIsValid, passwordIsValid, &&)
    >- signupButton.rx_subscribeEnabledTo
    >- disposeBag.addDisposable
```

Until then, maybe it would be better to temporarily do small workarounds like you've done?

**Comment by ashfurrow** [comment]
@kzaher I think the existing workarounds you pointed out are good approaches until swiftc catches up :) Thanks!
