### ISSUE TITLE
Consider Adding Continuous Integration

### ISSUE THREAD

**Issue by ashfurrow** [kzaher/RxSwift#45]
We should consider adding continuous integration from Travis or CircleCI. This would run tests on pull requests to make sure everything is :green_apple: before we merge :tada:

Happy to help out with this.

**Comment by kzaher** [comment]
Hi @ashfurrow,

yeah, sure. I'm all for that.

I've done some investigation for CircleCI, but it asked me for admin permission to all of my repositories, which unfortunately I cannot do.

That would mean that I would need to create a dummy github account just for that?

I'm sure you have more experience them I with that, so I would appreciate your help on this.

**Comment by ashfurrow** [comment]
Cool, I can take a look at that. I understand it's not practical to give access to app repos – a dummy account could work. Alternatively, if you're willing, we can use my account (I would need write access to the repo, which I totally understand if you're not OK with). I have already given CircleCI access to my account, so it's fine.

**Comment by kzaher** [comment]
I'm all for simple solutions :)

 I've added you as a collaborator, this should give you write access.

**Comment by ashfurrow** [comment]
Perfect – I'll try and get that setup this weekend.

**Comment by bontoJR** [comment]
The write access is not enough for CircleCI, as discussed and tested few months ago, it requires the repo ownership and Kruno can't give access to all repos. The good solution would be to Kruno to create an association being the administrator, but the RxSwift name has been taken and not used since last year. According to Github rules is a violation, but I don't know how much they would care about it. :(

**Comment by ashfurrow** [comment]
Huh, you're right. Looks like I can only have CI on _my fork_. Hmm. 

If it's OK with everyone, I can contact GitHub to see about getting the organization name.

**Comment by ashfurrow** [comment]
(That is, of course, if @kzaher wants to move it to an org.)

**Comment by bontoJR** [comment]
(I am on a phone, sorry for typos and missing words) 

I think Kruno is ok with that, we discussed this weeks ago, on that time the necessity wasn't big, now that the exposure of the project is getting bigger, it would probably make sense. I think the name is important, but on the other hand the Reactive scene has his own association, so I don't know if a dedicated one would be better than join the original one. The current RxSwift is an extreme accurate port of Rx.Net and has a lot to share with RxJava (some names and conventions are different, but mostly because of the language, not because of the implementation, as discussed in the Slack channel). I will let Kruno answer, also I would also love to push the website with valid tutorials and content, I will manage to draft a roadmap and publish it on Slack tomorrow.

**Comment by seivan** [comment]
Whats' wrong with Travis-CI? Worked great for me in the past.

**Comment by kzaher** [comment]
I've already contacted GitHub :)

The account doesn't have any publicly visible activity, but it isn't dormant. The person responded, but I didn't get the impression that he was willing to let the name go :(

In theory, I don't have an issue moving this project to RxSwift organization or to a part of some other organization, but I don't want to do it over night because I wanted to include CI for my repository.

It is also kind of backwards that continuous integration asks more then write access.

What is more weird is that I can't give it admin access to only one of repositories I have access to.

What's even more weird is that it can't integrate with write only access to my repository, but it can integrate with organizations what I am only member of and not admin. This is insane.

https://help.github.com/articles/about-third-party-application-restrictions/

> Note: When an organization has not set up third-party application restrictions, any third-party application authorized by an organization member can also access the organization's private resources.

Have I misunderstood something?

**Comment by ashfurrow** [comment]
Wow, that _is insane_. 

Travis doesn't let _me_ set up this repo, either. @kzaher: here's the list of permissions that Travis requested. It applies to all my orgs, too, which is silly. Why is it up to the org to opt out? Why can't I, as the user granting access, determine which orgs an app has access to?

<img width="484" alt="screen shot 2015-07-04 at 5 51 42 pm" src="https://cloud.githubusercontent.com/assets/498212/8509515/821a9d9c-2275-11e5-806b-000434d3eabe.png">

Dunno if that situation is acceptable, either. Quite the pickle.

Totally understand not wanting to transfer this to an org just for CI – we can keep this issue tucked away and reevaluate when it makes sense :smile:

**Comment by kzaher** [comment]
How can anyone accept to this?

<img width="500" alt="screen shot 2015-07-05 at 00 04 25" src="https://cloud.githubusercontent.com/assets/1641148/8509567/0dbc3a16-22aa-11e5-81ab-c3ab48d844b4.png">

**Comment by seivan** [comment]
@kzaher Is it the same between the Private Travis and the Open Source (public only) Travis?
You should ask them, I am sure they have gotten this before.

**Comment by ashfurrow** [comment]
It's pretty bananas, but I'm not on that many organizations with close source repos. Just @artsy, really, but it kind of freaks me out that _any_ Artsy org member could approve a malicious app by accident, then anyone could have access to _all_ our private repos – _all_ of Artsy's code. Some org members aren't developers and might not understand the significance of the approval. The more I think about this, the more I agree with you @kzaher.

**Comment by bontoJR** [comment]
Well, eventually I can write a script pulling from repo on github on a personal virtual machine and run the script using the ownership of a fork. This would workaround the ownership and Kruno can avoid to transfer the repo to an association just for CI. He's still the only one really writing and investing time on coding the core of the project, so CI wouldn't give any real advantage right now.

**Comment by bontoJR** [comment]
On core I mean operators, schedulers, subjects, etc... Most of the external commits are about RxCocoa or documentation/useful resources, so things that are not directly related to the necessity of having a CI on place for RxSwift :)

**Comment by kzaher** [comment]
I've thought about this, and I think I know what to do.

I need to create another github account for private client repositories and leave their organizations with this public account.

In that way CI tools will only have access to my public work.

It's a stupid solution, but the only one that is "low risk" and secure.

It will take some time to do this since I'm in the middle of some projects :(, but I'll start the process probably next week.

**Comment by kzaher** [comment]
I'm trying to add CircleCI

Warning: Sorry! Your build didn't run because we are still adding capacity to the iOS beta and haven't enabled your organization yet. We know you're waiting and we'll get you building as soon as we can. If you have any questions, please free to contact us in support.

:(

Does anybody know somebody there to help us? :)

**Comment by kzaher** [comment]
Hm, looks like Travis has a chance of working, I'll see if I can maybe set up Travis.

**Comment by kzaher** [comment]
I can finally say, considered, done :) :tada:

**Comment by ashfurrow** [comment]
:clap:
