### ISSUE TITLE
Public Roadmap

### ISSUE THREAD

**Issue by ashfurrow** [kzaher/RxSwift#46]
It'd be awesome to have a public roadmap of what RxSwift would need to implement to be considered "done" – we could have a Roadmap.md file in the repo that contains checks using GitHub markdown syntax:

- [ ] Still needs to be done
- [x] This is implemented

Or

-  Still needs to be done
- ~~This is implemented~~

So that if someone wants to contribute, they'll have an idea of where to start. 

Anyone have any thoughts?

**Comment by alcarvalho** [comment]
:+1: to that... since we already have a list of some kind in the `#next-features` of Slacker, it's just a matter of getting it out of there. A file on the repo would be much easier to find.

**Comment by ashfurrow** [comment]
Cool. I'm happy to take action if we're sure of a direction. I'm thinking we could copy all the operations from [here](http://reactivex.io/documentation/operators.html), and combine that with a list from the Slack room. Then I can check off things that've already been done. 

Does that sound reasonable?

**Comment by kzaher** [comment]
Hi guys,
you are right, the public facing information is now little stale. Sry about that, there are so many things happening, and I'm doing the best I can.

I've previously done wiki page that contains roadmap, but since it was stale, I've temporary removed it.

Right now the priority is RxCocoa refactoring, since we currently don't have a clear direction there.
That should be hopefully done this weekend.

Once that is done, I would be happy to resurrect that wiki page. The reason why I've chosen wiki page previously is because in that way I don't have to pollute commit history with commits that change checked state.
Is anyone ok with a wiki roadmap page?

I have a prototype of RxCocoa now that:
* enables reactive data sources
* has generic delegate to observable functionality (equivalent to rac_signalForSelector)
* enables parallel proxying of delegate messages to legacy delegate mechanism

It required me to add one objective c file (because Swift can't handle NSInvocation), but it solved a lot of problems.

I still haven't commited those changes to feature/rxcocoa-revamp (made them today).

What's happening in parallel now is that @seivan is trying to port RxSwift to Swift 2.0. I think she's near done with that.

Once RxCocoa revamp + creating Swift 2.0 is completed these are priorities as I see them:
* Adding wrappers for Cocoa/UIKit framework + unit tests (once revamp work is done, it should be pretty straightforward)
* Creating real RxSwift 2.0 version that fully uses Swift 2.0 features
* Documenting RxSwift specifics
* Creating project RxBlocking with blocking operators (for unit tests)
* Adding new operators

If somebody has some other wishes, you can ask in this thread for now.

Just need little more time :)

**Comment by seivan** [comment]
I've finished porting 
* RxSwift, 
* RxSwift tests 
 - 6 breaking tests related to ```let _ =``` and ``` _ =``` not retaining a disposable in the scope.
* RxCocoa
* RxCocoaTests

It's nearing midnight, so I won't be able to finish RxCocoaSamples tonight :sleeping:

**Comment by kzaher** [comment]
:+1:

**Comment by ashfurrow** [comment]
Awesome, this sounds awesome. Please just let me know what I can do to assist. 

@kzaher please _do not_ apologize for not having done enough. This is a great project that you've started on your own time. You don't owe us anything. I'm just happy to contribute to an important community project.

**Comment by kzaher** [comment]
Hi, I've added public wiki roadmap.

**Comment by ashfurrow** [comment]
Cool!
