### ISSUE TITLE
I miss more documentation

### ISSUE THREAD

**Issue by carlosypunto** [kzaher/RxSwift#5]
Good job, I'm really happy with this library, I like much more than RAC 3.0. I am new to the FRP world and I miss some more documentation and simplest example.The GitHubSignup example is quite clear but WikipediaImageSearch see it a little complicated.
I miss documentation in the code.

**Comment by carlosypunto** [comment]
Perhaps [this example](https://github.com/carlosypunto/ReallySimpleMVVMExampleWithRxSwift) is too simple, but if I can understand the complete library I would like to make a number of easy to difficult examples of use.

**Comment by carlosypunto** [comment]
¿If it's not too much trouble and is not too much you could implement [this example](https://github.com/carlosypunto/MVVMSwiftSample) or something similar with your library?

**Comment by kzaher** [comment]
I do think that the project needs a lot more documentation and examples.

I'm interested in hearing your pain points while using this project or reading the code.

Since this kind of feedback has significant value to this project, and this is probably inefficient way of collecting all of the pain points, feel free to contact me on my email and setting up some kind of meeting.

I'm really interested in collecting this valuable feedback more efficiently and providing you an explanation for all of the confusing parts.

Kruno

**Comment by desseim** [comment]
Although the documentation is great, I ran across a point of confusion for several people in the comparison to RAC section.

I've seen a discussion where people interpreted this section as stating that Rx described sequences of events while RAC was implemented as signals, and RxSwift as sequences.
They argued that RAC was actually implemented as sequences of events while the original Rx was about signals (the other way around).

I'm not familiar enough with RAC nor RxSwift to know better, but that got me interested as my understanding of Rx is that it deals with sequences of events, and I understood the aforementioned documentation section to state that Rx was about sequences, as opposed to the concept of signals, but I don't see it stating explicitly RAC is implemented as signals either.

So I'm curious of which it is, and of the concrete differences with RAC in general, and think that the project would benefit greatly from making this clearer :)

**Comment by dtartaglia** [comment]
In the "Introduction to Rx" book, the word "signal" appears a grand total of 5 times whereas the word "sequence" appears several hundred times...

I think Rx is about sequences, not signals.

**Comment by kzaher** [comment]
Hi @desseim,
        @dtartaglia is correct. From what I understand, the abstraction underlying Rx is sequence.

        I also didn't see word signal mentioned anywhere in Rx.Net source code repository.

        The main class in RAC is called signal :) and sequences aren't mentioned anywhere. I totally understand your confusion, and has the same doubts some time ago, but it looks like RAC signals have some different properties then sequences.

        According to RAC 3.0-beta6, signals can change ordering of values (otherwise observeOn operator has bug for concurrent schedulers). RAC 3.0-beta6 also has a concept of interrupted signal, which is really hard to fit in abstraction of sequences.

        Unfortunately, I don't know if observeOn has a bug or it's possible for signals to change ordering of elements. I couldn't find documentation anywhere specifying properties of signals, so you will need to ask RAC project maintainers for more info about this.

        Hope this clears things up for you.

**Comment by desseim** [comment]
Thanks, this matches with my understanding as well (regarding Rx).

What confused me was a RAC maintainer stating that the allegation about signal values arriving out of order was "not true" and a misunderstanding of how RAC works (it was on the slack RAC channel in case anyone is interested).
As someone new to both RAC and RxSwift I want to understand the difference better and I think it would be nice to make it clearer for anyone else in this situation. As RAC seems to be [confusing a few terms](https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1342), anyone looking for FRP or reactive extension on iOS or Cocoa is likely to end up there, so I think it'd make sense to strengthen that README part about the differences between RAC and RxSwift.

I could certainly see a clearer attribution of this signal and ordering examples to RAC (see my original post) and links to sources to back up these assertions beneficial to the clarity of the README.

It may also just be me and anyone with a good experience of RAC wouldn't care as much though, so just take it as a suggestion :)

**Comment by kzaher** [comment]
Hi, I agree about a need to strengthen the difference between RAC and RxSwift, and I do believe it's confusing right now.

The more I think about it, I think that best thing to do would be to write a couple of examples of parallel RAC and RxSwift code.

I never intended to say that RAC signals can swap element orderings for sure, I only meant to say that it's a confusing concept and that they don't define properties of signal anywhere, so I have no idea can signal elements actually do that, and is that a valid signal. The fact that you've had to contact one of the team members proves that the confusion is real.

However, I will remove those sentences about changing orderings from documentation because I don't want to mislead people. I've definitely learned a lot from RAC team, and wouldn't want to cause any damage to their reputation in this way. This change will be released in a day or two with next release 1.5

Parallel examples will have to wait until 1.6 or 1.7.

@desseim appreciate the feedback

Kruno

**Comment by kzaher** [comment]
@desseim Sry, I'm now reading my last response, I've actually said that they change ordering values. That was a mistake of mine.

**Comment by desseim** [comment]
@kzaher Wholeheartedly agree with each one of your points.
And thanks for planning on making things clearer !

**Comment by kzaher** [comment]
Hi guys,
this issue was opened a long time ago :) I feel comfortable closing it now. If we still feel there are some specific areas that need specific documentation attention, please nominate those areas in issues.

Since it was opened lot of things have happened.

* We've been featured on [http://reactivex.io/](http://reactivex.io/), and since we were trying to consolidate our efforts with broader Rx community anyway, we'll reference that portal as our official documentation portal, and unify all naming. 
I see this as an excellent way or defining documentation/naming source of truth.
The only thing this project still needs to do is document peculiarities of Swift integration. 
But I think that huge steps forward have been made toward unification. `RxSwift` operator names are also being added to that portal, so documentation is improving significantly (@carlosypunto has also helped us with that).


* Since there were some complaints regarding the way we compared ourselves with ReactiveCocoa, I've removed that comparison to avoid any further confusion, and accidentally cause any damage to that project.
For now, our README.md contains basic difference between those two projects, and other similar projects.
There will be further improvements to documentation in the future.
As far as for more detailed description of differences, I'm hoping that with time community will create enough materials to help people more easily decide which one to use.
This project's documentation will focus in the future on communicating the strengths of `RxSwift` in a better and clearer way :)
Unfortunately, we'll just need some time to do it properly.
